# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HT_search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1143, 845)
        self.gridLayout_7 = QtGui.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 1)
        self.RP_HT_input_field = QtGui.QLineEdit(self.tab_2)
        self.RP_HT_input_field.setObjectName(_fromUtf8("RP_HT_input_field"))
        self.gridLayout_9.addWidget(self.RP_HT_input_field, 0, 1, 1, 1)
        self.RP_HT_input_button = QtGui.QPushButton(self.tab_2)
        self.RP_HT_input_button.setObjectName(_fromUtf8("RP_HT_input_button"))
        self.gridLayout_9.addWidget(self.RP_HT_input_button, 0, 2, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_9)
        spacerItem2 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.RP_heat_map = PlotWidget(self.tab_2)
        self.RP_heat_map.setObjectName(_fromUtf8("RP_heat_map"))
        self.verticalLayout_2.addWidget(self.RP_heat_map)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.HT_RP_plot_EICs = QtGui.QCheckBox(self.tab_2)
        self.HT_RP_plot_EICs.setObjectName(_fromUtf8("HT_RP_plot_EICs"))
        self.horizontalLayout_5.addWidget(self.HT_RP_plot_EICs)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.RP_mascot_input_field = QtGui.QLineEdit(self.tab_2)
        self.RP_mascot_input_field.setObjectName(_fromUtf8("RP_mascot_input_field"))
        self.horizontalLayout_4.addWidget(self.RP_mascot_input_field)
        self.RP_mascot_input_button = QtGui.QPushButton(self.tab_2)
        self.RP_mascot_input_button.setObjectName(_fromUtf8("RP_mascot_input_button"))
        self.horizontalLayout_4.addWidget(self.RP_mascot_input_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.RP_mzDelta = QtGui.QLineEdit(self.tab_2)
        self.RP_mzDelta.setObjectName(_fromUtf8("RP_mzDelta"))
        self.horizontalLayout.addWidget(self.RP_mzDelta)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.RP_EIC_width = QtGui.QLineEdit(self.tab_2)
        self.RP_EIC_width.setObjectName(_fromUtf8("RP_EIC_width"))
        self.horizontalLayout_2.addWidget(self.RP_EIC_width)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.RP_min_intensity = QtGui.QLineEdit(self.tab_2)
        self.RP_min_intensity.setObjectName(_fromUtf8("RP_min_intensity"))
        self.horizontalLayout_6.addWidget(self.RP_min_intensity)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_3.addWidget(self.label_19)
        self.RP_output_file_field = QtGui.QLineEdit(self.tab_2)
        self.RP_output_file_field.setObjectName(_fromUtf8("RP_output_file_field"))
        self.horizontalLayout_3.addWidget(self.RP_output_file_field)
        self.RP_output_file_button = QtGui.QPushButton(self.tab_2)
        self.RP_output_file_button.setObjectName(_fromUtf8("RP_output_file_button"))
        self.horizontalLayout_3.addWidget(self.RP_output_file_button)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.RP_run_button = QtGui.QPushButton(self.tab_2)
        self.RP_run_button.setObjectName(_fromUtf8("RP_run_button"))
        self.horizontalLayout_7.addWidget(self.RP_run_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.HT_RV_load_results = QtGui.QPushButton(self.tab_6)
        self.HT_RV_load_results.setObjectName(_fromUtf8("HT_RV_load_results"))
        self.horizontalLayout_22.addWidget(self.HT_RV_load_results)
        self.RV_reset = QtGui.QPushButton(self.tab_6)
        self.RV_reset.setObjectName(_fromUtf8("RV_reset"))
        self.horizontalLayout_22.addWidget(self.RV_reset)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.HT_RV_hitlist = QtGui.QTableWidget(self.tab_6)
        self.HT_RV_hitlist.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.HT_RV_hitlist.setObjectName(_fromUtf8("HT_RV_hitlist"))
        self.HT_RV_hitlist.setColumnCount(4)
        self.HT_RV_hitlist.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_hitlist.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.HT_RV_hitlist)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.HT_RV_up = QtGui.QPushButton(self.tab_6)
        self.HT_RV_up.setObjectName(_fromUtf8("HT_RV_up"))
        self.horizontalLayout_23.addWidget(self.HT_RV_up)
        self.HT_RV_down = QtGui.QPushButton(self.tab_6)
        self.HT_RV_down.setObjectName(_fromUtf8("HT_RV_down"))
        self.horizontalLayout_23.addWidget(self.HT_RV_down)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.label_28 = QtGui.QLabel(self.tab_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_7.addWidget(self.label_28)
        self.HT_RV_accepted_list = QtGui.QTableWidget(self.tab_6)
        self.HT_RV_accepted_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.HT_RV_accepted_list.setAlternatingRowColors(False)
        self.HT_RV_accepted_list.setObjectName(_fromUtf8("HT_RV_accepted_list"))
        self.HT_RV_accepted_list.setColumnCount(4)
        self.HT_RV_accepted_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.HT_RV_accepted_list.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.HT_RV_accepted_list)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.HT_RV_remove = QtGui.QPushButton(self.tab_6)
        self.HT_RV_remove.setObjectName(_fromUtf8("HT_RV_remove"))
        self.horizontalLayout_24.addWidget(self.HT_RV_remove)
        self.HT_RV_write = QtGui.QPushButton(self.tab_6)
        self.HT_RV_write.setObjectName(_fromUtf8("HT_RV_write"))
        self.horizontalLayout_24.addWidget(self.HT_RV_write)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_21 = QtGui.QLabel(self.tab_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_25.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.tab_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_25.addWidget(self.label_22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.HT_RV_HM_widget = PlotWidget(self.tab_6)
        self.HT_RV_HM_widget.setObjectName(_fromUtf8("HT_RV_HM_widget"))
        self.horizontalLayout_26.addWidget(self.HT_RV_HM_widget)
        self.HT_RV_EIC = PlotWidget(self.tab_6)
        self.HT_RV_EIC.setObjectName(_fromUtf8("HT_RV_EIC"))
        self.horizontalLayout_26.addWidget(self.HT_RV_EIC)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_27.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_27.addWidget(self.label_24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.HT_RV_MS = PlotWidget(self.tab_6)
        self.HT_RV_MS.setObjectName(_fromUtf8("HT_RV_MS"))
        self.verticalLayout_8.addWidget(self.HT_RV_MS)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.HT_RV_accept = QtGui.QPushButton(self.tab_6)
        self.HT_RV_accept.setObjectName(_fromUtf8("HT_RV_accept"))
        self.horizontalLayout_28.addWidget(self.HT_RV_accept)
        self.HT_RV_reject = QtGui.QPushButton(self.tab_6)
        self.HT_RV_reject.setObjectName(_fromUtf8("HT_RV_reject"))
        self.horizontalLayout_28.addWidget(self.HT_RV_reject)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_9.setText(_translate("Dialog", "HiTIME Output File", None))
        self.RP_HT_input_button.setText(_translate("Dialog", "Browse", None))
        self.label_16.setText(_translate("Dialog", "Heat Map", None))
        self.HT_RP_plot_EICs.setText(_translate("Dialog", "Plot EICs", None))
        self.label_15.setText(_translate("Dialog", "mzML File", None))
        self.RP_mascot_input_button.setText(_translate("Dialog", "Browse", None))
        self.label_17.setText(_translate("Dialog", "mzDelta", None))
        self.label_18.setText(_translate("Dialog", "EIC Width", None))
        self.label_14.setText(_translate("Dialog", "Minimum Intensity", None))
        self.label_19.setText(_translate("Dialog", "Output File", None))
        self.RP_output_file_button.setText(_translate("Dialog", "Browse", None))
        self.RP_run_button.setText(_translate("Dialog", "Run Postprocessing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Results Postprocessing", None))
        self.HT_RV_load_results.setText(_translate("Dialog", "Load Results", None))
        self.RV_reset.setText(_translate("Dialog", "Reset", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "RT", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.HT_RV_hitlist.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Score", None))
        self.HT_RV_up.setText(_translate("Dialog", "Up", None))
        self.HT_RV_down.setText(_translate("Dialog", "Down", None))
        self.label_28.setText(_translate("Dialog", "Accepted Hits", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hit", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "RT", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.HT_RV_accepted_list.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Score", None))
        self.HT_RV_remove.setText(_translate("Dialog", "Remove", None))
        self.HT_RV_write.setText(_translate("Dialog", "Write Results to File", None))
        self.label_21.setText(_translate("Dialog", "Heat Map", None))
        self.label_22.setText(_translate("Dialog", "EIC", None))
        self.label_23.setText(_translate("Dialog", "MS1 Spectrum", None))
        self.HT_RV_accept.setText(_translate("Dialog", "Accept", None))
        self.HT_RV_reject.setText(_translate("Dialog", "Reject", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Results Viewer", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

